Found local copy...
Loading...
Done!
[I 2025-09-05 23:15:47,340] A new study created in RDB with name: __init__
[I 2025-09-05 23:16:14,176] A new study created in RDB with name: RDKitFP_KNN_Lipophilicity_AstraZeneca_1
[I 2025-09-05 23:16:17,030] A new study created in RDB with name: RDKitFP_KNN_Lipophilicity_AstraZeneca_2
[I 2025-09-05 23:16:19,626] A new study created in RDB with name: RDKitFP_KNN_Lipophilicity_AstraZeneca_3
[I 2025-09-05 23:16:24,576] A new study created in RDB with name: RDKitFP_KNN_Lipophilicity_AstraZeneca_0
[I 2025-09-05 23:17:10,040] Trial 0 finished with value: 1.0099408023809524 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'metric': 'manhattan'}. Best is trial 0 with value: 1.0099408023809524.
[I 2025-09-05 23:17:10,050] Trial 0 finished with value: 1.0193931773809526 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 0 with value: 1.0193931773809526.
[I 2025-09-05 23:17:10,137] Trial 0 finished with value: 1.0869753361992944 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 0 with value: 1.0869753361992944.
[I 2025-09-05 23:17:29,205] Trial 1 finished with value: 0.996453856264746 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'metric': 'minkowski'}. Best is trial 1 with value: 0.996453856264746.
[I 2025-09-05 23:17:29,227] Trial 1 finished with value: 1.287243640327557 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'metric': 'chebyshev'}. Best is trial 0 with value: 1.0099408023809524.
[I 2025-09-05 23:17:29,311] Trial 1 finished with value: 0.9637924187434718 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'metric': 'minkowski'}. Best is trial 1 with value: 0.9637924187434718.
[I 2025-09-05 23:17:29,382] Trial 0 finished with value: 1.043145601387249 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'metric': 'manhattan'}. Best is trial 0 with value: 1.043145601387249.
[I 2025-09-05 23:17:44,799] Trial 1 finished with value: 1.421040482804233 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'metric': 'chebyshev'}. Best is trial 0 with value: 1.043145601387249.
[I 2025-09-05 23:17:44,833] Trial 2 finished with value: 1.307440844222899 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'metric': 'chebyshev'}. Best is trial 1 with value: 0.9637924187434718.
[I 2025-09-05 23:17:44,863] Trial 2 finished with value: 1.058296121031746 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 1 with value: 0.996453856264746.
[I 2025-09-05 23:18:51,846] Trial 2 finished with value: 1.3909677845238093 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'metric': 'chebyshev'}. Best is trial 0 with value: 1.0099408023809524.
[I 2025-09-05 23:18:51,941] A new study created in RDB with name: RDKitFP_KNN_Lipophilicity_AstraZeneca_5
[I 2025-09-05 23:18:52,087] A new study created in RDB with name: RDKitFP_KNN_Lipophilicity_AstraZeneca_6
[I 2025-09-05 23:19:01,435] A new study created in RDB with name: RDKitFP_KNN_Lipophilicity_AstraZeneca_4
[I 2025-09-05 23:19:17,603] Trial 3 finished with value: 1.3277198736637512 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'metric': 'chebyshev'}. Best is trial 0 with value: 1.0099408023809524.
[I 2025-09-05 23:19:52,144] Trial 0 finished with value: 0.9448467002155729 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 0 with value: 0.9448467002155729.
[I 2025-09-05 23:19:52,216] Trial 4 finished with value: 1.0380080524399844 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 0 with value: 1.0099408023809524.
[I 2025-09-05 23:19:52,252] Trial 0 finished with value: 0.9353858071661837 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 0 with value: 0.9353858071661837.
[W 2025-09-05 23:20:11,377] Trial 5 failed with parameters: {'n_neighbors': 7} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 77, in _create_scoped_session
    yield session
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 598, in _set_trial_param_without_commit
    trial = models.TrialModel.find_or_raise_by_id(trial_id, session)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 270, in find_or_raise_by_id
    trial = query.one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
    return self._iter().one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT trials.trial_id AS trials_trial_id, trials.number AS trials_number, trials.study_id AS trials_study_id, trials.state AS trials_state, trials.datetime_start AS trials_datetime_start, trials.datetime_complete AS trials_datetime_complete 
FROM trials 
WHERE trials.trial_id = ?]
[parameters: (20,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 81, in objective
    hyperparams = model_class.get_hyperparameter_space(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/models.py", line 385, in get_hyperparameter_space
    'weights': trial.suggest_categorical('weights', ['uniform', 'distance']),
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 406, in suggest_categorical
    return self._suggest(name, CategoricalDistribution(choices=choices))
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 641, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 169, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 95, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2025-09-05 23:20:11,384] Trial 5 failed with value None.
[W 2025-09-05 23:20:11,388] Trial 1 failed with parameters: {} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 77, in _create_scoped_session
    yield session
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 598, in _set_trial_param_without_commit
    trial = models.TrialModel.find_or_raise_by_id(trial_id, session)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 270, in find_or_raise_by_id
    trial = query.one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
    return self._iter().one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT trials.trial_id AS trials_trial_id, trials.number AS trials_number, trials.study_id AS trials_study_id, trials.state AS trials_state, trials.datetime_start AS trials_datetime_start, trials.datetime_complete AS trials_datetime_complete 
FROM trials 
WHERE trials.trial_id = ?]
[parameters: (21,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 81, in objective
    hyperparams = model_class.get_hyperparameter_space(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/models.py", line 384, in get_hyperparameter_space
    'n_neighbors': trial.suggest_categorical('n_neighbors', [3, 5, 7, 9, 11]),
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 406, in suggest_categorical
    return self._suggest(name, CategoricalDistribution(choices=choices))
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 641, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 169, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 95, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2025-09-05 23:20:11,389] Trial 1 failed with value None.
[I 2025-09-05 23:20:48,019] Trial 0 finished with value: 1.091871463990555 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'metric': 'manhattan'}. Best is trial 0 with value: 1.091871463990555.
[I 2025-09-05 23:20:53,973] A new study created in RDB with name: RDKitFP_KNN_Lipophilicity_AstraZeneca_7
[I 2025-09-05 23:21:18,898] A new study created in RDB with name: RDKitFP_KNN_Lipophilicity_AstraZeneca_8
[W 2025-09-05 23:22:09,505] Trial 0 failed with parameters: {} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 77, in _create_scoped_session
    yield session
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 807, in _get_trials
    models.StudyModel.find_or_raise_by_id(study_id, session)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 71, in find_or_raise_by_id
    study = query.one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
    return self._iter().one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT studies.study_id AS studies_study_id, studies.study_name AS studies_study_name 
FROM studies 
WHERE studies.study_id = ?]
[parameters: (9,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 81, in objective
    hyperparams = model_class.get_hyperparameter_space(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/models.py", line 384, in get_hyperparameter_space
    'n_neighbors': trial.suggest_categorical('n_neighbors', [3, 5, 7, 9, 11]),
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 406, in suggest_categorical
    return self._suggest(name, CategoricalDistribution(choices=choices))
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 635, in _suggest
    param_value = self.study.sampler.sample_independent(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/samplers/_tpe/sampler.py", line 455, in sample_independent
    trials = study._get_trials(deepcopy=False, states=states, use_cache=True)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/study.py", line 277, in _get_trials
    self._thread_local.cached_all_trials = self._storage.get_all_trials(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 219, in get_all_trials
    self._read_trials_from_remote_storage(study_id)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 240, in _read_trials_from_remote_storage
    trials = self._backend._get_trials(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 857, in _get_trials
    trials = [self._build_frozen_trial_from_trial_model(trial) for trial in trial_models]
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 95, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2025-09-05 23:22:09,507] Trial 0 failed with value None.
[I 2025-09-05 23:22:28,514] Trial 1 finished with value: 1.3136736676089342 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'chebyshev'}. Best is trial 0 with value: 1.091871463990555.
[I 2025-09-05 23:22:38,102] A new study created in RDB with name: RDKitFP_KNN_Lipophilicity_AstraZeneca_9
[I 2025-09-05 23:24:02,494] Trial 0 finished with value: 0.9462665911086684 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 0 with value: 0.9462665911086684.
[I 2025-09-05 23:24:12,826] Trial 0 finished with value: 1.060468743926142 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 0 with value: 1.060468743926142.
[I 2025-09-05 23:24:12,853] Trial 2 finished with value: 1.001509407998251 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'minkowski'}. Best is trial 2 with value: 1.001509407998251.
[I 2025-09-05 23:24:58,240] Trial 1 finished with value: 1.3983662857142858 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'metric': 'chebyshev'}. Best is trial 0 with value: 0.9462665911086684.
[I 2025-09-05 23:24:58,263] Trial 1 finished with value: 1.0470372123015874 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'metric': 'manhattan'}. Best is trial 1 with value: 1.0470372123015874.
[I 2025-09-05 23:24:58,287] Trial 3 finished with value: 1.0489618258017492 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 2 with value: 1.001509407998251.
[I 2025-09-05 23:25:25,220] Trial 2 finished with value: 0.9707713041851317 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 2 with value: 0.9707713041851317.
[I 2025-09-05 23:25:25,242] Trial 2 finished with value: 1.0355560161564625 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'metric': 'manhattan'}. Best is trial 0 with value: 0.9462665911086684.
[I 2025-09-05 23:25:25,285] Trial 4 finished with value: 0.9519102114979806 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 4 with value: 0.9519102114979806.
[I 2025-09-05 23:25:45,426] Trial 5 finished with value: 1.3402180170878535 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'metric': 'chebyshev'}. Best is trial 4 with value: 0.9519102114979806.
[I 2025-09-05 23:25:45,448] Trial 3 finished with value: 0.9452772643089518 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 3 with value: 0.9452772643089518.
[I 2025-09-05 23:25:45,470] Trial 3 finished with value: 1.352526600273185 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'chebyshev'}. Best is trial 2 with value: 0.9707713041851317.
[I 2025-09-05 23:26:23,727] Trial 4 finished with value: 1.0722698456790123 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 2 with value: 0.9707713041851317.
[I 2025-09-05 23:26:28,348] Trial 6 finished with value: 0.9804950374623634 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'metric': 'minkowski'}. Best is trial 4 with value: 0.9519102114979806.
[I 2025-09-05 23:26:42,184] Trial 4 finished with value: 1.3983662857142858 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'metric': 'chebyshev'}. Best is trial 3 with value: 0.9452772643089518.
[I 2025-09-05 23:27:56,988] Trial 7 finished with value: 1.001509407998251 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'minkowski'}. Best is trial 4 with value: 0.9519102114979806.
[I 2025-09-05 23:28:11,412] Trial 5 finished with value: 1.060468743926142 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 2 with value: 0.9707713041851317.
[I 2025-09-05 23:28:20,795] Trial 5 finished with value: 1.3681169223688145 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'metric': 'chebyshev'}. Best is trial 3 with value: 0.9452772643089518.
[I 2025-09-05 23:28:51,016] Trial 6 finished with value: 1.368032833259847 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'metric': 'chebyshev'}. Best is trial 3 with value: 0.9452772643089518.
[I 2025-09-05 23:28:51,038] Trial 6 finished with value: 0.9678308567307156 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 6 with value: 0.9678308567307156.
[I 2025-09-05 23:28:51,078] Trial 8 finished with value: 1.3446274441205053 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'metric': 'chebyshev'}. Best is trial 4 with value: 0.9519102114979806.
[I 2025-09-05 23:29:10,316] Trial 7 finished with value: 0.9678308567307156 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 6 with value: 0.9678308567307156.
[I 2025-09-05 23:29:19,712] Trial 7 finished with value: 0.9587383091028909 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'metric': 'minkowski'}. Best is trial 3 with value: 0.9452772643089518.
[I 2025-09-05 23:29:19,742] Trial 9 finished with value: 1.3112658016671082 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'metric': 'chebyshev'}. Best is trial 4 with value: 0.9519102114979806.
[I 2025-09-05 23:29:38,549] Trial 8 finished with value: 1.0978718676210153 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 6 with value: 0.9678308567307156.
[I 2025-09-05 23:30:16,276] Trial 10 finished with value: 1.0134479927248679 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'metric': 'manhattan'}. Best is trial 4 with value: 0.9519102114979806.
[I 2025-09-05 23:30:30,193] Trial 8 finished with value: 0.9976009695305856 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'metric': 'minkowski'}. Best is trial 3 with value: 0.9452772643089518.
[I 2025-09-05 23:31:46,763] Trial 9 finished with value: 1.009685401028836 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'metric': 'minkowski'}. Best is trial 6 with value: 0.9678308567307156.
[I 2025-09-05 23:31:56,083] Trial 11 finished with value: 0.9519102114979806 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 4 with value: 0.9519102114979806.
[I 2025-09-05 23:31:56,102] Trial 9 finished with value: 1.0395168683862435 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 3 with value: 0.9452772643089518.
[I 2025-09-05 23:32:52,471] Trial 10 finished with value: 0.9509742579454591 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 3 with value: 0.9452772643089518.
[I 2025-09-05 23:33:04,729] Trial 10 finished with value: 1.4155841155270972 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'metric': 'chebyshev'}. Best is trial 6 with value: 0.9678308567307156.
[I 2025-09-05 23:33:04,735] Trial 12 finished with value: 0.9519102114979806 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 4 with value: 0.9519102114979806.
[I 2025-09-05 23:33:55,804] Trial 11 finished with value: 0.9678308567307156 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 6 with value: 0.9678308567307156.
[I 2025-09-05 23:34:03,360] Trial 13 finished with value: 0.9519102114979806 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 4 with value: 0.9519102114979806.
[I 2025-09-05 23:34:17,583] Trial 11 finished with value: 0.9462665911086684 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 3 with value: 0.9452772643089518.
[I 2025-09-05 23:35:49,510] Trial 14 finished with value: 0.9490260573605239 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 14 with value: 0.9490260573605239.
[I 2025-09-05 23:35:49,521] Trial 12 finished with value: 0.9462665911086684 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 3 with value: 0.9452772643089518.
[I 2025-09-05 23:35:49,552] Trial 12 finished with value: 0.9678308567307156 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 6 with value: 0.9678308567307156.
[I 2025-09-05 23:36:22,804] Trial 13 finished with value: 0.9678308567307156 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 6 with value: 0.9678308567307156.
[I 2025-09-05 23:36:22,826] Trial 13 finished with value: 0.9509742579454591 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 3 with value: 0.9452772643089518.
[I 2025-09-05 23:37:47,978] Trial 14 finished with value: 0.9345973115970406 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 14 with value: 0.9345973115970406.
[I 2025-09-05 23:37:47,985] Trial 14 finished with value: 0.9725949294966529 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 6 with value: 0.9678308567307156.
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 77, in _create_scoped_session
    yield session
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 916, in get_best_trial
    trial_id = models.TrialModel.find_min_value_trial_id(study_id, 0, session)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 227, in find_min_value_trial_id
    session.query(cls)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
    return self._iter().one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT trials.trial_id AS trials_trial_id 
FROM trials JOIN trial_values ON trials.trial_id = trial_values.trial_id 
WHERE trials.study_id = ? AND trials.state = ? AND trial_values.objective = ? ORDER BY CASE WHEN (trial_values.value_type = ?) THEN ? WHEN (trial_values.value_type = ?) THEN ? WHEN (trial_values.value_type = ?) THEN ? END ASC, trial_values.value ASC
 LIMIT ? OFFSET ?]
[parameters: (2, 'COMPLETE', 0, 'INF_NEG', -1, 'FINITE', 0, 'INF_POS', 1, 1, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 97, in run_single_experiment
    best_hyperparams = self.run_hyperparameter_optimization(
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 85, in run_hyperparameter_optimization
    study.optimize(objective, n_trials=env.N_TRIALS)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/study.py", line 490, in optimize
    _optimize(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial_id = _run_trial(study, func, catch)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 229, in _run_trial
    study._log_completed_trial(values, trial.number, trial.params)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/study.py", line 1158, in _log_completed_trial
    best_trial = self._get_best_trial(deepcopy=False)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/study.py", line 308, in _get_best_trial
    best_trial = self._storage.get_best_trial(self._study_id)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 180, in get_best_trial
    return self._backend.get_best_trial(study_id)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 916, in get_best_trial
    trial_id = models.TrialModel.find_min_value_trial_id(study_id, 0, session)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 95, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/./code/main.py", line 18, in <module>
    manager.run_nested_cv(fingerprint, model_name, dataset_name)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 136, in run_nested_cv
    raise exc
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 131, in run_nested_cv
    seed_result, test_predictions, test_indices = future.result()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
