Found local copy...
Loading...
Done!
[I 2025-09-06 01:25:15,592] A new study created in RDB with name: __init__
[I 2025-09-06 01:25:42,292] A new study created in RDB with name: MACCS_KNN_PAMPA_NCATS_3
[I 2025-09-06 01:25:42,306] A new study created in RDB with name: MACCS_KNN_PAMPA_NCATS_1
[I 2025-09-06 01:25:42,321] A new study created in RDB with name: MACCS_KNN_PAMPA_NCATS_2
[I 2025-09-06 01:25:42,365] A new study created in RDB with name: MACCS_KNN_PAMPA_NCATS_0
[I 2025-09-06 01:25:55,501] Trial 0 finished with value: 0.45098286867141724 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 0 with value: 0.45098286867141724.
[I 2025-09-06 01:25:55,532] Trial 0 finished with value: 0.4587293267250061 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'metric': 'minkowski'}. Best is trial 0 with value: 0.4587293267250061.
[I 2025-09-06 01:26:11,636] Trial 0 finished with value: 0.45676177740097046 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 0 with value: 0.45676177740097046.
[I 2025-09-06 01:26:11,663] Trial 1 finished with value: 0.4588356614112854 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'metric': 'chebyshev'}. Best is trial 0 with value: 0.45098286867141724.
[I 2025-09-06 01:26:11,701] Trial 0 finished with value: 0.45602354407310486 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'metric': 'chebyshev'}. Best is trial 0 with value: 0.45602354407310486.
[I 2025-09-06 01:26:12,031] Trial 2 finished with value: 0.45002493262290955 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 2 with value: 0.45002493262290955.
[I 2025-09-06 01:26:26,293] Trial 1 finished with value: 0.46591588854789734 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'metric': 'chebyshev'}. Best is trial 0 with value: 0.4587293267250061.
[I 2025-09-06 01:26:26,311] Trial 1 finished with value: 0.45599955320358276 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'metric': 'manhattan'}. Best is trial 1 with value: 0.45599955320358276.
[I 2025-09-06 01:26:26,332] Trial 1 finished with value: 0.4612736701965332 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'metric': 'chebyshev'}. Best is trial 0 with value: 0.45676177740097046.
[I 2025-09-06 01:26:26,355] Trial 3 finished with value: 0.45889750123023987 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'metric': 'chebyshev'}. Best is trial 2 with value: 0.45002493262290955.
[I 2025-09-06 01:26:42,259] Trial 4 finished with value: 0.45002493262290955 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 2 with value: 0.45002493262290955.
[I 2025-09-06 01:26:42,275] Trial 2 finished with value: 0.45812496542930603 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 2 with value: 0.45812496542930603.
[I 2025-09-06 01:26:42,369] Trial 2 finished with value: 0.4634712040424347 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'metric': 'chebyshev'}. Best is trial 0 with value: 0.45676177740097046.
[I 2025-09-06 01:27:26,957] Trial 3 finished with value: 0.4634712040424347 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'metric': 'chebyshev'}. Best is trial 0 with value: 0.45676177740097046.
[I 2025-09-06 01:27:26,998] Trial 3 finished with value: 0.4580906331539154 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'metric': 'chebyshev'}. Best is trial 3 with value: 0.4580906331539154.
[I 2025-09-06 01:27:27,117] Trial 5 finished with value: 0.44744279980659485 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'metric': 'manhattan'}. Best is trial 5 with value: 0.44744279980659485.
[I 2025-09-06 01:28:41,014] A new study created in RDB with name: MACCS_KNN_PAMPA_NCATS_4
[I 2025-09-06 01:28:41,140] A new study created in RDB with name: MACCS_KNN_PAMPA_NCATS_5
[I 2025-09-06 01:28:41,235] A new study created in RDB with name: MACCS_KNN_PAMPA_NCATS_6
[I 2025-09-06 01:29:31,869] Trial 6 finished with value: 0.450601726770401 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'minkowski'}. Best is trial 5 with value: 0.44744279980659485.
[W 2025-09-06 01:29:31,885] Trial 0 failed with parameters: {'n_neighbors': 5, 'weights': 'distance'} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 77, in _create_scoped_session
    yield session
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 598, in _set_trial_param_without_commit
    trial = models.TrialModel.find_or_raise_by_id(trial_id, session)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 270, in find_or_raise_by_id
    trial = query.one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
    return self._iter().one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT trials.trial_id AS trials_trial_id, trials.number AS trials_number, trials.study_id AS trials_study_id, trials.state AS trials_state, trials.datetime_start AS trials_datetime_start, trials.datetime_complete AS trials_datetime_complete 
FROM trials 
WHERE trials.trial_id = ?]
[parameters: (23,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 81, in objective
    hyperparams = model_class.get_hyperparameter_space(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/models.py", line 386, in get_hyperparameter_space
    'metric': trial.suggest_categorical('metric', ['minkowski', 'manhattan', 'chebyshev']),
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 406, in suggest_categorical
    return self._suggest(name, CategoricalDistribution(choices=choices))
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 641, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 169, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 95, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2025-09-06 01:29:31,886] Trial 0 failed with value None.
[I 2025-09-06 01:29:31,898] Trial 0 finished with value: 0.45118215680122375 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 0 with value: 0.45118215680122375.
[I 2025-09-06 01:30:07,067] Trial 0 finished with value: 0.46157926321029663 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'chebyshev'}. Best is trial 0 with value: 0.46157926321029663.
[I 2025-09-06 01:30:07,120] A new study created in RDB with name: MACCS_KNN_PAMPA_NCATS_8
[I 2025-09-06 01:30:38,631] Trial 7 finished with value: 0.4477998912334442 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'metric': 'manhattan'}. Best is trial 5 with value: 0.44744279980659485.
[I 2025-09-06 01:30:38,690] Trial 0 finished with value: 0.4561850130558014 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'metric': 'manhattan'}. Best is trial 0 with value: 0.4561850130558014.
[I 2025-09-06 01:31:01,420] Trial 1 finished with value: 0.46068307757377625 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'metric': 'chebyshev'}. Best is trial 1 with value: 0.46068307757377625.
[I 2025-09-06 01:31:01,440] Trial 1 finished with value: 0.4551754295825958 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'metric': 'chebyshev'}. Best is trial 0 with value: 0.45118215680122375.
[I 2025-09-06 01:31:01,462] Trial 1 finished with value: 0.46155521273612976 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'metric': 'chebyshev'}. Best is trial 0 with value: 0.4561850130558014.
[I 2025-09-06 01:31:01,515] Trial 8 finished with value: 0.4463714361190796 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 8 with value: 0.4463714361190796.
[I 2025-09-06 01:31:35,447] A new study created in RDB with name: MACCS_KNN_PAMPA_NCATS_9
[I 2025-09-06 01:32:41,195] Trial 9 finished with value: 0.45105844736099243 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'metric': 'manhattan'}. Best is trial 8 with value: 0.4463714361190796.
[I 2025-09-06 01:32:41,218] Trial 0 finished with value: 0.46309006214141846 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'chebyshev'}. Best is trial 0 with value: 0.46309006214141846.
[I 2025-09-06 01:33:07,261] Trial 1 finished with value: 0.4579773545265198 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'minkowski'}. Best is trial 1 with value: 0.4579773545265198.
[I 2025-09-06 01:33:07,281] Trial 10 finished with value: 0.4463714361190796 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 8 with value: 0.4463714361190796.
[I 2025-09-06 01:33:39,500] Trial 11 finished with value: 0.4463714361190796 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 8 with value: 0.4463714361190796.
[I 2025-09-06 01:33:39,518] Trial 2 finished with value: 0.4537194073200226 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'metric': 'minkowski'}. Best is trial 2 with value: 0.4537194073200226.
[I 2025-09-06 01:34:04,901] Trial 12 finished with value: 0.45170390605926514 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 8 with value: 0.4463714361190796.
[I 2025-09-06 01:34:04,924] Trial 3 finished with value: 0.45881518721580505 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'metric': 'manhattan'}. Best is trial 2 with value: 0.4537194073200226.
[I 2025-09-06 01:34:30,133] Trial 4 finished with value: 0.4617028534412384 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'metric': 'minkowski'}. Best is trial 2 with value: 0.4537194073200226.
[I 2025-09-06 01:34:30,157] Trial 13 finished with value: 0.4463714361190796 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 8 with value: 0.4463714361190796.
[I 2025-09-06 01:35:03,232] Trial 5 finished with value: 0.45712924003601074 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 2 with value: 0.4537194073200226.
[I 2025-09-06 01:35:03,252] Trial 14 finished with value: 0.457396924495697 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'metric': 'chebyshev'}. Best is trial 8 with value: 0.4463714361190796.
[I 2025-09-06 01:36:39,606] Trial 6 finished with value: 0.45685794949531555 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 2 with value: 0.4537194073200226.
[I 2025-09-06 01:38:01,038] Trial 7 finished with value: 0.46268489956855774 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'metric': 'chebyshev'}. Best is trial 2 with value: 0.4537194073200226.
[I 2025-09-06 01:38:01,348] Trial 8 finished with value: 0.4546329081058502 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 2 with value: 0.4537194073200226.
[I 2025-09-06 01:38:01,588] Trial 9 finished with value: 0.4617028534412384 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'metric': 'minkowski'}. Best is trial 2 with value: 0.4537194073200226.
[I 2025-09-06 01:38:01,856] Trial 10 finished with value: 0.45329025387763977 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 10 with value: 0.45329025387763977.
[I 2025-09-06 01:38:02,095] Trial 11 finished with value: 0.45329025387763977 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 10 with value: 0.45329025387763977.
[I 2025-09-06 01:38:02,334] Trial 12 finished with value: 0.45329025387763977 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 10 with value: 0.45329025387763977.
[I 2025-09-06 01:38:02,585] Trial 13 finished with value: 0.45329025387763977 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 10 with value: 0.45329025387763977.
[I 2025-09-06 01:38:02,966] Trial 14 finished with value: 0.46147608757019043 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'metric': 'chebyshev'}. Best is trial 10 with value: 0.45329025387763977.
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 77, in _create_scoped_session
    yield session
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 779, in get_trial
    trial_model = models.TrialModel.find_or_raise_by_id(trial_id, session)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 270, in find_or_raise_by_id
    trial = query.one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
    return self._iter().one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT trials.trial_id AS trials_trial_id, trials.number AS trials_number, trials.study_id AS trials_study_id, trials.state AS trials_state, trials.datetime_start AS trials_datetime_start, trials.datetime_complete AS trials_datetime_complete 
FROM trials 
WHERE trials.trial_id = ?]
[parameters: (14,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    updated_state, values, warning_message = _tell_with_warning(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_tell.py", line 106, in _tell_with_warning
    frozen_trial = _get_frozen_trial(study, trial)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_tell.py", line 40, in _get_frozen_trial
    return study._storage.get_trial(trial_id)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 211, in get_trial
    return self._backend.get_trial(trial_id)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 780, in get_trial
    frozen_trial = self._build_frozen_trial_from_trial_model(trial_model)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 95, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 97, in run_single_experiment
    best_hyperparams = self.run_hyperparameter_optimization(
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 85, in run_hyperparameter_optimization
    study.optimize(objective, n_trials=env.N_TRIALS)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/study.py", line 490, in optimize
    _optimize(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial_id = _run_trial(study, func, catch)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    assert False, "Should not reach."
AssertionError: Should not reach.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/./code/main.py", line 18, in <module>
    manager.run_nested_cv(fingerprint, model_name, dataset_name)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 136, in run_nested_cv
    raise exc
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 131, in run_nested_cv
    seed_result, test_predictions, test_indices = future.result()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
AssertionError: Should not reach.
