Found local copy...
Loading...
Done!
[I 2025-09-06 01:21:46,243] A new study created in RDB with name: __init__
[I 2025-09-06 01:21:46,564] A new study created in RDB with name: RDKitFP_ElasticNet_PAMPA_NCATS_0
[I 2025-09-06 01:21:46,633] A new study created in RDB with name: RDKitFP_ElasticNet_PAMPA_NCATS_1
[I 2025-09-06 01:21:46,729] A new study created in RDB with name: RDKitFP_ElasticNet_PAMPA_NCATS_2
[I 2025-09-06 01:21:47,393] A new study created in RDB with name: RDKitFP_ElasticNet_PAMPA_NCATS_3
[I 2025-09-06 01:30:02,372] Trial 0 finished with value: 0.4679965078830719 and parameters: {'alpha': 0.597044126303578, 'l1_ratio': 0.24266941882772503}. Best is trial 0 with value: 0.4679965078830719.
[I 2025-09-06 01:30:02,373] Trial 0 finished with value: 0.46400314569473267 and parameters: {'alpha': 0.8156964899388113, 'l1_ratio': 0.8005334893755586}. Best is trial 0 with value: 0.46400314569473267.
[I 2025-09-06 01:30:02,426] Trial 0 finished with value: 0.46575766801834106 and parameters: {'alpha': 0.09432302938817598, 'l1_ratio': 0.510555293615726}. Best is trial 0 with value: 0.46575766801834106.
[I 2025-09-06 01:30:02,499] A new study created in RDB with name: RDKitFP_ElasticNet_PAMPA_NCATS_4
[W 2025-09-06 01:31:23,969] Trial 1 failed with parameters: {'alpha': 7.797158697678829} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 77, in _create_scoped_session
    yield session
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 598, in _set_trial_param_without_commit
    trial = models.TrialModel.find_or_raise_by_id(trial_id, session)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 270, in find_or_raise_by_id
    trial = query.one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
    return self._iter().one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT trials.trial_id AS trials_trial_id, trials.number AS trials_number, trials.study_id AS trials_study_id, trials.state AS trials_state, trials.datetime_start AS trials_datetime_start, trials.datetime_complete AS trials_datetime_complete 
FROM trials 
WHERE trials.trial_id = ?]
[parameters: (7,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 81, in objective
    hyperparams = model_class.get_hyperparameter_space(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/models.py", line 362, in get_hyperparameter_space
    'l1_ratio': trial.suggest_float('l1_ratio', 0.1, 0.9),
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 161, in suggest_float
    suggested_value = self._suggest(name, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 641, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 169, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 95, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2025-09-06 01:31:24,030] Trial 1 failed with value None.
[W 2025-09-06 01:31:48,726] Trial 0 failed with parameters: {} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 77, in _create_scoped_session
    yield session
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 598, in _set_trial_param_without_commit
    trial = models.TrialModel.find_or_raise_by_id(trial_id, session)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 270, in find_or_raise_by_id
    trial = query.one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
    return self._iter().one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT trials.trial_id AS trials_trial_id, trials.number AS trials_number, trials.study_id AS trials_study_id, trials.state AS trials_state, trials.datetime_start AS trials_datetime_start, trials.datetime_complete AS trials_datetime_complete 
FROM trials 
WHERE trials.trial_id = ?]
[parameters: (8,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 81, in objective
    hyperparams = model_class.get_hyperparameter_space(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/models.py", line 361, in get_hyperparameter_space
    'alpha': trial.suggest_float('alpha', 0.001, 10, log=True),
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 161, in suggest_float
    suggested_value = self._suggest(name, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 641, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 169, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 95, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2025-09-06 01:31:48,727] Trial 0 failed with value None.
[I 2025-09-06 01:33:08,273] A new study created in RDB with name: RDKitFP_ElasticNet_PAMPA_NCATS_5
[I 2025-09-06 01:34:12,372] A new study created in RDB with name: RDKitFP_ElasticNet_PAMPA_NCATS_7
[I 2025-09-06 01:34:19,909] Trial 1 finished with value: 0.46876904368400574 and parameters: {'alpha': 0.05377920074102075, 'l1_ratio': 0.2521308347282415}. Best is trial 0 with value: 0.46400314569473267.
[I 2025-09-06 01:34:19,980] Trial 1 finished with value: 0.4698266088962555 and parameters: {'alpha': 0.06500620193822322, 'l1_ratio': 0.4292217201245755}. Best is trial 0 with value: 0.4679965078830719.
[I 2025-09-06 01:41:14,370] Trial 0 finished with value: 0.47524839639663696 and parameters: {'alpha': 0.04989219851681723, 'l1_ratio': 0.48782620751172756}. Best is trial 0 with value: 0.47524839639663696.
[I 2025-09-06 01:41:20,385] Trial 2 finished with value: 0.4691639244556427 and parameters: {'alpha': 0.34438893356968175, 'l1_ratio': 0.5309392148591322}. Best is trial 0 with value: 0.4679965078830719.
[I 2025-09-06 01:41:39,077] Trial 0 finished with value: 0.47206541895866394 and parameters: {'alpha': 0.07163176160154264, 'l1_ratio': 0.24059499852706656}. Best is trial 0 with value: 0.47206541895866394.
[I 2025-09-06 01:41:39,138] Trial 2 finished with value: 0.46946951746940613 and parameters: {'alpha': 0.0053483170475807475, 'l1_ratio': 0.7717911767631674}. Best is trial 0 with value: 0.46400314569473267.
[I 2025-09-06 01:47:38,831] Trial 3 finished with value: 0.4550105333328247 and parameters: {'alpha': 5.196987050815828, 'l1_ratio': 0.8380944899463086}. Best is trial 3 with value: 0.4550105333328247.
[I 2025-09-06 01:47:42,188] Trial 3 finished with value: 0.4616580009460449 and parameters: {'alpha': 3.7446203694269418, 'l1_ratio': 0.5347394988903194}. Best is trial 3 with value: 0.4616580009460449.
[I 2025-09-06 01:47:42,203] Trial 1 finished with value: 0.4740809500217438 and parameters: {'alpha': 0.13264554102878198, 'l1_ratio': 0.24250253356548568}. Best is trial 1 with value: 0.4740809500217438.
[I 2025-09-06 01:48:01,314] A new study created in RDB with name: RDKitFP_ElasticNet_PAMPA_NCATS_9
[I 2025-09-06 01:48:01,346] A new study created in RDB with name: RDKitFP_ElasticNet_PAMPA_NCATS_8
[I 2025-09-06 01:54:53,857] Trial 4 finished with value: 0.46853557229042053 and parameters: {'alpha': 0.0698670079978908, 'l1_ratio': 0.33110251155454007}. Best is trial 3 with value: 0.4550105333328247.
[I 2025-09-06 01:55:32,780] Trial 0 finished with value: 0.46620067954063416 and parameters: {'alpha': 0.027034817832869235, 'l1_ratio': 0.5048063013842831}. Best is trial 0 with value: 0.46620067954063416.
[I 2025-09-06 01:56:11,883] Trial 0 finished with value: 0.4688926637172699 and parameters: {'alpha': 0.05460204708293238, 'l1_ratio': 0.3441245980154075}. Best is trial 0 with value: 0.4688926637172699.
[I 2025-09-06 02:01:16,911] Trial 5 finished with value: 0.46970298886299133 and parameters: {'alpha': 0.002050412712799178, 'l1_ratio': 0.47469660779832457}. Best is trial 3 with value: 0.4550105333328247.
[I 2025-09-06 02:01:39,985] Trial 1 finished with value: 0.4665818214416504 and parameters: {'alpha': 0.04599394004165521, 'l1_ratio': 0.183808915404177}. Best is trial 0 with value: 0.46620067954063416.
[I 2025-09-06 02:01:56,820] Trial 1 finished with value: 0.4691261649131775 and parameters: {'alpha': 0.0014247212546736364, 'l1_ratio': 0.3726060061407538}. Best is trial 0 with value: 0.4688926637172699.
[I 2025-09-06 02:04:27,360] Trial 2 finished with value: 0.45938852429389954 and parameters: {'alpha': 9.21652515012685, 'l1_ratio': 0.6208935047521817}. Best is trial 2 with value: 0.45938852429389954.
[I 2025-09-06 02:06:17,785] Trial 6 finished with value: 0.4669629633426666 and parameters: {'alpha': 0.35857873955587843, 'l1_ratio': 0.12899354297058585}. Best is trial 3 with value: 0.4550105333328247.
[I 2025-09-06 02:06:30,319] Trial 2 finished with value: 0.4691261649131775 and parameters: {'alpha': 0.0019137628165008683, 'l1_ratio': 0.36966495582026715}. Best is trial 0 with value: 0.4688926637172699.
[I 2025-09-06 02:11:30,581] Trial 7 finished with value: 0.46946951746940613 and parameters: {'alpha': 0.007355493340585956, 'l1_ratio': 0.1317097205473469}. Best is trial 3 with value: 0.4550105333328247.
[I 2025-09-06 02:11:30,585] Trial 3 finished with value: 0.4638109803199768 and parameters: {'alpha': 5.760223717064188, 'l1_ratio': 0.694291581616663}. Best is trial 3 with value: 0.4638109803199768.
[I 2025-09-06 02:11:30,597] Trial 3 finished with value: 0.46666765213012695 and parameters: {'alpha': 0.0023853577725455716, 'l1_ratio': 0.5393122077885911}. Best is trial 2 with value: 0.45938852429389954.
[I 2025-09-06 02:15:01,305] Trial 4 finished with value: 0.4688926637172699 and parameters: {'alpha': 0.03335237209321283, 'l1_ratio': 0.6101787248434967}. Best is trial 3 with value: 0.4638109803199768.
[I 2025-09-06 02:15:01,340] Trial 4 finished with value: 0.4631172716617584 and parameters: {'alpha': 0.45145905037859635, 'l1_ratio': 0.8771500162750369}. Best is trial 2 with value: 0.45938852429389954.
[I 2025-09-06 02:18:31,371] Trial 5 finished with value: 0.4682539999485016 and parameters: {'alpha': 0.19445287954028107, 'l1_ratio': 0.47611546570311836}. Best is trial 3 with value: 0.4638109803199768.
[I 2025-09-06 02:18:31,391] Trial 5 finished with value: 0.4619738459587097 and parameters: {'alpha': 0.3973175973382363, 'l1_ratio': 0.7595252980239173}. Best is trial 2 with value: 0.45938852429389954.
[I 2025-09-06 02:22:16,496] Trial 6 finished with value: 0.4670865535736084 and parameters: {'alpha': 0.1777786268935505, 'l1_ratio': 0.7555914783095073}. Best is trial 3 with value: 0.4638109803199768.
[I 2025-09-06 02:22:16,517] Trial 6 finished with value: 0.46596717834472656 and parameters: {'alpha': 0.032662187969219256, 'l1_ratio': 0.6147653896656962}. Best is trial 2 with value: 0.45938852429389954.
[I 2025-09-06 02:26:20,357] Trial 7 finished with value: 0.46820592880249023 and parameters: {'alpha': 0.3745658788278476, 'l1_ratio': 0.6889103374602412}. Best is trial 3 with value: 0.4638109803199768.
[I 2025-09-06 02:26:20,384] Trial 7 finished with value: 0.46666765213012695 and parameters: {'alpha': 0.0018323383441741067, 'l1_ratio': 0.6570733902714416}. Best is trial 2 with value: 0.45938852429389954.
[I 2025-09-06 02:29:58,765] Trial 8 finished with value: 0.46456626057624817 and parameters: {'alpha': 0.05341487723081239, 'l1_ratio': 0.8730153963256465}. Best is trial 2 with value: 0.45938852429389954.
[I 2025-09-06 02:29:58,788] Trial 8 finished with value: 0.4691261649131775 and parameters: {'alpha': 0.0012100295874021218, 'l1_ratio': 0.8417701442016797}. Best is trial 3 with value: 0.4638109803199768.
[I 2025-09-06 02:33:09,850] Trial 9 finished with value: 0.4639550745487213 and parameters: {'alpha': 1.604924818225457, 'l1_ratio': 0.8524219595234136}. Best is trial 2 with value: 0.45938852429389954.
[I 2025-09-06 02:33:24,446] Trial 9 finished with value: 0.4691261649131775 and parameters: {'alpha': 0.0038197814003000435, 'l1_ratio': 0.6997753295887789}. Best is trial 3 with value: 0.4638109803199768.
[I 2025-09-06 02:35:20,007] Trial 10 finished with value: 0.46111899614334106 and parameters: {'alpha': 8.684796630691755, 'l1_ratio': 0.3189081009439397}. Best is trial 2 with value: 0.45938852429389954.
[I 2025-09-06 02:35:20,029] Trial 10 finished with value: 0.4607240557670593 and parameters: {'alpha': 9.135979136066622, 'l1_ratio': 0.14523053239457928}. Best is trial 10 with value: 0.4607240557670593.
[I 2025-09-06 02:37:39,143] Trial 11 finished with value: 0.4605901837348938 and parameters: {'alpha': 8.477451317640472, 'l1_ratio': 0.2986809010877979}. Best is trial 2 with value: 0.45938852429389954.
[I 2025-09-06 02:37:39,201] Trial 11 finished with value: 0.4624442756175995 and parameters: {'alpha': 7.108471892702921, 'l1_ratio': 0.11991473553402193}. Best is trial 10 with value: 0.4607240557670593.
[I 2025-09-06 02:39:40,990] Trial 12 finished with value: 0.45960819721221924 and parameters: {'alpha': 9.874495860187514, 'l1_ratio': 0.3605406515124001}. Best is trial 2 with value: 0.45938852429389954.
[I 2025-09-06 02:39:41,020] Trial 12 finished with value: 0.4607240557670593 and parameters: {'alpha': 9.487673278995043, 'l1_ratio': 0.13094405367286682}. Best is trial 10 with value: 0.4607240557670593.
[I 2025-09-06 02:43:08,713] Trial 13 finished with value: 0.4655757546424866 and parameters: {'alpha': 1.4332789143046754, 'l1_ratio': 0.10270321225045913}. Best is trial 10 with value: 0.4607240557670593.
[I 2025-09-06 02:43:08,734] Trial 13 finished with value: 0.4628974497318268 and parameters: {'alpha': 2.4490296628498487, 'l1_ratio': 0.35777454549070137}. Best is trial 2 with value: 0.45938852429389954.
[I 2025-09-06 02:46:32,576] Trial 14 finished with value: 0.46794843673706055 and parameters: {'alpha': 1.2264090219941266, 'l1_ratio': 0.22434520748967324}. Best is trial 10 with value: 0.4607240557670593.
[I 2025-09-06 02:47:00,973] Trial 14 finished with value: 0.46289753913879395 and parameters: {'alpha': 1.9854212827064217, 'l1_ratio': 0.41490072084296953}. Best is trial 2 with value: 0.45938852429389954.
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 77, in _create_scoped_session
    yield session
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 369, in get_study_system_attrs
    models.StudyModel.find_or_raise_by_id(study_id, session)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 71, in find_or_raise_by_id
    study = query.one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
    return self._iter().one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT studies.study_id AS studies_study_id, studies.study_name AS studies_study_name 
FROM studies 
WHERE studies.study_id = ?]
[parameters: (5,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 97, in run_single_experiment
    best_hyperparams = self.run_hyperparameter_optimization(
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 85, in run_hyperparameter_optimization
    study.optimize(objective, n_trials=env.N_TRIALS)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/study.py", line 490, in optimize
    _optimize(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial_id = _run_trial(study, func, catch)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 229, in _run_trial
    study._log_completed_trial(values, trial.number, trial.params)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/study.py", line 1134, in _log_completed_trial
    metric_names = self.metric_names
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/study.py", line 386, in metric_names
    return self._storage.get_study_system_attrs(self._study_id).get(_SYSTEM_ATTR_METRIC_NAMES)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 141, in get_study_system_attrs
    return self._backend.get_study_system_attrs(study_id)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 371, in get_study_system_attrs
    system_attrs = {attr.key: json.loads(attr.value_json) for attr in attributes}
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 95, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/./code/main.py", line 18, in <module>
    manager.run_nested_cv(fingerprint, model_name, dataset_name)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 136, in run_nested_cv
    raise exc
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 131, in run_nested_cv
    seed_result, test_predictions, test_indices = future.result()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
